---

- name: Notification 
  ansible.builtin.debug:
    msg: Going to create user/group {{ user }}

- name: create group
  ansible.builtin.group:
    name: "{{ user }}"
    state: present

- name: create user
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ user }}"
    create_home: false
    state: present