---
- name: enabled-chaind
  ansible.builtin.systemd:
    name: chaind
    enabled: true
    daemon_reload: true
    state: started
  become: true

- name: restart-chaind
  ansible.builtin.service:
    name: chaind
    state: restarted
  become: true
