---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enabled-teku
  ansible.builtin.systemd:
    name: teku
    state: started
    enabled: yes

- name: restart-teku
  ansible.builtin.service:
    name: teku
    state: restarted