---
- name: enabled-teku
  ansible.builtin.systemd:
    name: teku
    enabled: trues
    daemon_reload: true
    state: started
  become: true

- name: restart-teku
  ansible.builtin.service:
    name: teku
    state: restarted
  become: true
