---
- name: Setup
  hosts: all

  roles:
    - { role: common, tags: common }

- hosts: _teku
  vars:
    teku_restport: 5051

  roles:
    - { role: teku, tags: teku }

- hosts: _chaind
  vars:
    teku_restport: 5051

  roles:
    - { role: chaind, tags: chaind }