---
- name: create user/group
  include_role:
    name: common
    tasks_from: create-user.yml
  vars:
    user: "{{ username }}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/chaind
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/log/chaind
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"

- name: install binary
  include_tasks: update-binary.yml

- name: update configs
  include_tasks: update-configs.yml

- name: update services
  include_tasks: update-services.yml
